name: 000-kubeflow
namespace: argocd
additionalLabels: {}
additionalAnnotations: {}
finalizers:
  - resources-finalizer.argocd.argoproj.io
project: default
repoURL: ghcr.io/treebeardtech/helm
targetRevision: "0.3.1-dev+2024-03-13-T19-04-39"
chart: kubeflow-core
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: false
    selfHeal: false
