apiVersion: batch/v1
kind: Job
metadata:
  name: 005-deps-finished
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      serviceAccount: argocd-server
      containers:
      - name: check-sync
        image: bitnami/kubectl
        command: ["/bin/sh","-c"]
        args:
        - |
          echo waiting
          date
          sleep 20
          echo done
          date
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 30