{{ if .Values.certManager.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 003-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{ .Values.certManager.spec | toYaml | indent 2}}
{{- end -}}