# derived from https://artifacthub.io/packages/helm/argo/argocd-apps/1.6.2?modal=template&template=applications.yaml
{{- with .Values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  project: {{ .project }}
  {{- with .source }}
  source:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sources:
  - repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    chart: {{ .chart }}
    helm:
      {{- with .valuesObject }}
      valuesObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .values }}
      values:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .valueFiles }}
      valueFiles:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- range .sources }}
  - repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    ref: {{ .ref }}
  {{- end }}
  destination:
    {{- toYaml .destination | nindent 4 }}
  {{- with .syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .info }}
  info:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}