{{ if .Values.oidcAuthService.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 009-oidc-authservice
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{ .Values.oidcAuthService.spec | toYaml | indent 2 }}
{{- end -}}
